import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import TableList from "~/components/tables/table-list";
import Button from "~/components/buttons/Button";

const Home = () => {

  const { data } = api.posts.home.useQuery()




  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-100">

        <h1 className="text-black text-lg my-3 text-center">Posts available</h1>

        <Button className="my-8 ">
          <Link href={{
            pathname: '/posts/create',
          }}>Add post</Link>

        </Button>


        <div className="flex flex-col">

          <TableList posts={data ?? []} />

        </div>
      </div >

    </>
  );
};

export default Home;


