import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import TableList from "~/components/tables/table-list";

const Home = () => {

  const { data } = api.posts.home.useQuery()




  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Products available</h1>
      <div className="flex flex-col">
        <TableList data={[{ id: 23, name: 'my name' }]} />

      </div>
    </>
  );
};

export default Home;


